---
GitLab:
  Endpoint: ad.example.com
  User: username
  Pass: password

Confluence:
  Endpoint: ad.example.com
  User: username
  Pass: password
  Page: 12345678
  Space: DevOps
  Prefix: Prefix

Projects:
  112: "DevOps"
